###################
# ENV VARS:
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Check for new releases
# Automatically check for new releases (new versions)

on:
  schedule:
    - cron: "0 1 */1 * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch release version
        id: fetch-version
        run: |
          curl -sL https://raw.githubusercontent.com/n8n-io/n8n/master/package.json | jq -r ".version" > release-versions/n8n-latest.txt
          echo ::set-output name=release::$(cat release-versions/n8n-latest.txt)

      #      - name: Fetch release version
      #        id: fetch-version
      #        uses: pozetroninc/github-action-get-latest-release@master
      #        with:
      #          owner: n8n-io
      #          repo: n8n
      #          excludes: prerelease, draft
      #      - name: Fetch release version
      #        run: |
      #          echo "${{ steps.fetch-version.outputs.release }}" > release-versions/n8n-latest.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New auto release v${{ steps.fetch-version.outputs.release }}